server:
  port: 9090
  stored:
    file:
      path: C:\\files\\uploads\\

spring:
  main:
    allow-bean-definition-overriding: true

    http:
      encoding:
        charset: UTF-8
        enabled: true
        force: true

  jwt:
    secret: vmfhaltmskdlstkfkdgodyroqkfwkdbalroqkfwkdbalaaaaaaaaaaaaaaaabbbbb

  web:
    resources:
      static-locations: file:///C:/jikpick_uploads/

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 200MB

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://jikpick.cniogu4geuvu.ap-northeast-2.rds.amazonaws.com:3306/jikpick?useUnicode=true&characterEncoding=utf8mb4
    username: testdb
    password: 123456789
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 50
      minimum-idle: 1
      idle-timeout: 5000
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: bus00216@gmail.com
    password: kdhs bfnl cuso ysvg
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    database: mysql
    generate-ddl: false
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        generate_statistics: false
        format_sql: true
        use_sql_comments: false
        cache:
          use_second_level_cache: false
          use_query_cache: false
          region.factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory

  thymeleaf:
    cache: false
    check-template-location: true
    encoding: utf-8
    servlet:
      content-type: text/html
    prefix: file:src/main/resources/templates/
    suffix: .html

  devtools:
    livereload:
      enabled: true
    remote:
      restart:
        enabled: true
    restart:
      enabled: true

mybatis:
  config-location: classpath:config/mybatis-config.xml
  mapper-locations: classpath:mapper/**/*.xml

logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure: OFF
        web: DEBUG
      thymeleaf: OFF
      hibernate:
        sql: INFO
        type: OFF

kakao:
  rest-api-key: "KakaoAK <REST_API_KEY>"
